# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xci
# IP: The module: 'videoClk108MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xci
# IP: The module: 'videoClk108MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'videoClk108MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
