# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/BresenhamLineDraw.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/configColors.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/displayMouseSprite.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/divideBy3.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/hex_to_sseg_p.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/led_mux8_p.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/orderedDither.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/ps2_top.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/ps2rx.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/ps2tx.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/sketchFrame.sv}
  {C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10_VideoSketch.sv}
}
read_verilog -library xil_defaultlib {{C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/mouse.v}}
read_ip -quiet {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/videoClk108MHz/videoClk108MHz_ooc.xdc}}]

read_ip -quiet {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/frameBuffer/frameBuffer.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10.srcs/sources_1/ip/frameBuffer/frameBuffer_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10_VideoSketch.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Axelb/Documents/School/WSU Spring 2019/ECE 324/Lab10/Lab10_VideoSketch.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Lab10_VideoSketch -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab10_VideoSketch.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab10_VideoSketch_utilization_synth.rpt -pb Lab10_VideoSketch_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
